import React, { useRef } from 'react';
import { AssessmentResult, Currency } from '../../../types';
import AnalysisHeader from './AnalysisHeader';
import AnalysisVisuals from './AnalysisVisuals';
import AnalysisCostOverview from './AnalysisCostOverview';
import AnalysisCharts from './AnalysisCharts';
import { usePdfGenerator } from '../hooks/usePdfGenerator';

interface AnalysisDashboardProps {
  result: AssessmentResult;
  imageUrl: string;
  currency: Currency;
  onReset: () => void;
}

const AnalysisDashboard: React.FC<AnalysisDashboardProps> = ({ result, imageUrl, currency, onReset }) => {
  const visualizerRef = useRef<HTMLDivElement>(null);
  const { isGeneratingPdf, generatePdf } = usePdfGenerator();
  
  const handlePrint = () => {
    window.print();
  };

  const handleDownloadPDF = () => {
    generatePdf(result, currency, visualizerRef.current);
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <AnalysisHeader 
        onReset={onReset} 
        onPrint={handlePrint}
        onDownloadPdf={handleDownloadPDF}
        isGeneratingPdf={isGeneratingPdf}
      />

      {/* Main Content Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        
        {/* Left Column: Visuals */}
        <div className="lg:col-span-7">
           <AnalysisVisuals imageUrl={imageUrl} result={result} visualizerRef={visualizerRef} />
        </div>

        {/* Right Column: Data & Costs */}
        <div className="lg:col-span-5 space-y-6">
          <AnalysisCostOverview result={result} currency={currency} />
          <AnalysisCharts result={result} currency={currency} />
        </div>
      </div>
      
      {/* Footer for Print */}
      <div className="hidden print:block mt-8 pt-8 border-t border-surface-200 text-center text-slate-400 text-sm">
        <p>Generated by AutoClaim AI on {new Date(result.timestamp).toLocaleDateString()}</p>
        <p>This report is an AI-generated estimate in {currency} and requires final validation by a certified adjuster.</p>
      </div>
    </div>
  );
};

export default AnalysisDashboard;
